// Source of truth for slide order.
// Each entry is the filename slug (filename minus `.mdx`).
// Reorder by moving lines. Add new slides by inserting filename here.
export const slideOrder = [
  "title",
  "what-is",
  "two-ways",
  "day-one",
  "first-steps",
  "models",
  "subagent-routing",
  "context-tokens",
  "clear-vs-compact",
  "config-section",
  "claude-md-placement",
  "sample-claude-md",
  "keep-it-concise",
  "claude-md-maintenance",
  "permissions",
  "memory",
  "skills-section",
  "skills",
  "skills-vs-mcp",
  "context7",
  "subagents",
  "skills-authoring-section",
  "skill-scope",
  "skill-anatomy",
  "skill-example",
  "skill-references",
  "build-your-own-cli",
  "three-skills",
  "hooks",
  "mcp-section",
  "mcp",
  "mcp-roundup",
  "uses-section",
  "uses",
  "real-prompts",
  "limits-section",
  "bad-at",
  "failure-modes",
  "trust-ladder",
  "mitigations",
  "security-section",
  "protect-secrets",
  "permission-controls",
  "untrusted-repos",
  "anti-patterns",
  "plan-mode",
  "tips-section",
  "mindset",
  "tips",
  "questions",
] as const;
